import fs from 'node:fs';
const basePath=process.argv[2]||'polygon-rush/l3n/out/BASELINE_PHYSICS_GATE_REPORT.json';
const candPath=process.argv[3]||'polygon-rush/l3n/out/PHYSICS_GATE_REPORT.json';
const outPath=process.argv[4]||'polygon-rush/l3n/out/PHYSICS_AB_REPORT.json';
const b=JSON.parse(fs.readFileSync(basePath,'utf8'));
const c=JSON.parse(fs.readFileSync(candPath,'utf8'));
const reasons=[];
if(!b.passed||!c.passed) reasons.push('one runtime gate did not pass');
if(c.settledRacers < b.settledRacers) reasons.push(`settled racers regressed ${b.settledRacers}->${c.settledRacers}`);
if(c.leadDistance < Math.max(4,b.leadDistance*0.78)) reasons.push(`lead movement regressed ${b.leadDistance}->${c.leadDistance}`);
if(c.maxSpeed < Math.max(2,b.maxSpeed*0.75)) reasons.push(`max speed regressed ${b.maxSpeed}->${c.maxSpeed}`);
if(c.hitEvents < 1) reasons.push('candidate produced no hit events');
const span=x=>x.verticalBounds[1]-x.verticalBounds[0];
if(span(c) > Math.max(8,span(b)*2.5)) reasons.push(`vertical instability increased ${span(b)}->${span(c)}`);
const movementRatio=c.leadDistance/b.leadDistance;
const speedRatio=c.maxSpeed/b.maxSpeed;
const stabilityScore=(c.settledRacers/5)*45 + Math.min(1.2,movementRatio)*25 + Math.min(1.2,speedRatio)*20 + (c.hitEvents>0?10:0);
const report={gate:'Polygon Rush L3N Baseline vs Candidate Runtime Gate',passed:reasons.length===0,reasons,baseline:{leadDistance:b.leadDistance,maxSpeed:b.maxSpeed,settledRacers:b.settledRacers,hitEvents:b.hitEvents,verticalBounds:b.verticalBounds},candidate:{leadDistance:c.leadDistance,maxSpeed:c.maxSpeed,settledRacers:c.settledRacers,hitEvents:c.hitEvents,verticalBounds:c.verticalBounds},ratios:{movement:movementRatio,speed:speedRatio},stabilityScore};
fs.writeFileSync(outPath,JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
if(!report.passed) process.exit(2);
