import fs from 'node:fs';
const ITERATIONS=1000;
const BASE={engineForce:10500,brakeForce:14500,lateralGain:6.0,lateralMassScale:1750,yawTorque:4300,handbrakeLateral:0.95,linearDamping:0.14,angularDamping:2.85,friction:0.48,restitution:0.0,hullHalfY:0.62,spawnLift:0.90,fixedDt:1/60,subSteps:4};
const LIMITS={engineForce:[9000,11800],brakeForce:[12500,17000],lateralGain:[4.2,7.2],yawTorque:[3500,5200],linearDamping:[0.08,0.22],angularDamping:[2.1,3.4],friction:[0.40,0.62],restitution:[0,0.05],spawnLift:[0.84,1.02]};
const STEPS={engineForce:900,brakeForce:1400,lateralGain:.8,yawTorque:650,linearDamping:.045,angularDamping:.3,friction:.065,restitution:.018,spawnLift:.055};
const KEYS=Object.keys(STEPS);function clamp(v,[a,b]){return Math.max(a,Math.min(b,v));}function seeded(seed){let s=seed>>>0;return()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296);}const rnd=seeded(1477002),noise=()=>rnd()*2-1;
function oneScenario(p,gripMul=1,loadMul=1){const dt=1/120;let speed=0,t=0,yaw=0,lat=0,maxLat=0,brakeStop=0,osc=0;for(let i=0;i<720;i++){speed=Math.max(0,speed+(((p.engineForce*loadMul)/1150)-p.linearDamping*speed*.8)*dt);t+=dt;if(speed>=27.78)break;}const accelTime=t;speed=25;for(let i=0;i<480;i++){const ss=Math.min(Math.abs(speed)/8,1);yaw+=(p.yawTorque/5000)*.62*ss*dt*.72;lat+=(yaw*speed*.14-lat*(p.lateralGain*p.friction*gripMul))*dt;maxLat=Math.max(maxLat,Math.abs(lat));osc+=Math.abs(lat)*dt;}speed=30;t=0;while(speed>.2&&t<8){speed=Math.max(0,speed-(((p.brakeForce*gripMul)/1450)+p.linearDamping*speed*.25)*dt);brakeStop+=speed*dt;t+=dt;}return{accelTime,maxLat,brakeStop,osc};}
function evaluate(p){const scenarios=[oneScenario(p,1,1),oneScenario(p,.78,.96),oneScenario(p,.60,.92)];const vals=[];for(const s of scenarios){let v=100;v-=Math.abs(s.accelTime-3.7)*4.8;v-=Math.max(0,s.maxLat-4.1)*4.6;v-=Math.abs(s.brakeStop-44)*.18;v-=Math.max(0,s.osc-12)*.06;vals.push(v);}let value=vals.reduce((a,b)=>a+b,0)/vals.length-Math.max(0,94-Math.min(...vals))*.65;const penetration=Math.max(0,(p.hullHalfY+.10)-p.spawnLift);value-=penetration*160+p.restitution*24;value-=Math.max(0,(p.yawTorque-5000)/200)*3.5;value-=Math.max(0,(p.friction-.58)/.01)*1.8;value-=Math.max(0,.87-p.spawnLift)*80;for(const k of KEYS){const[a,b]=LIMITS[k],range=b-a,d=Math.min(p[k]-a,b-p[k])/range;if(d<.05)value-=(.05-d)*40;}const trust={engineForce:1100,brakeForce:1800,lateralGain:1.2,yawTorque:850,linearDamping:.07,angularDamping:.55,friction:.11,restitution:.05,spawnLift:.12};let drift=0;for(const k of KEYS)drift+=Math.pow((p[k]-BASE[k])/trust[k],2);value-=Math.max(0,drift-4)*.55;return{value,scenarios,worst:Math.min(...vals),drift};}
function curve(i,plateau){const x=i/ITERATIONS;let phase,scale,explore;if(x<.2){phase='explore';scale=1;explore=.75}else if(x<.55){phase='learn';scale=.58;explore=.45}else if(x<.85){phase='exploit';scale=.28;explore=.22}else{phase='polish';scale=.10;explore=.08}if(plateau>80){phase='escape';scale=Math.min(.8,scale*1.9);explore=Math.min(.75,explore+.3)}return{phase,scale,explore};}
function mutate(parent,c,elite){const q={...parent},count=c.explore>.6?3:c.explore>.3?2:1,keys=[...KEYS].sort(()=>rnd()-.5).slice(0,count);for(const k of keys){let center=parent[k];if(elite&&rnd()<.35)center=(center+elite[k])*.5;q[k]=clamp(center+noise()*STEPS[k]*c.scale,LIMITS[k]);}return q;}
let best={...BASE},bestEval=evaluate(best),accepted=0,plateau=0;const elites=[{p:{...best},e:bestEval}],history=[],curveSummary={};for(let i=1;i<=ITERATIONS;i++){const c=curve(i,plateau),anchor=(rnd()<.15&&elites.length>1)?elites[Math.floor(rnd()*Math.min(6,elites.length))].p:best,cand=mutate(anchor,c,elites[0]?.p),ev=evaluate(cand),gain=ev.value-bestEval.value,accept=gain>.0002&&ev.worst>=bestEval.worst-.25;if(accept){best=cand;bestEval=ev;accepted++;plateau=0;elites.push({p:{...best},e:bestEval});elites.sort((a,b)=>b.e.value-a.e.value);elites.length=Math.min(8,elites.length)}else plateau++;const b=Math.floor((i-1)/100)*100+100;curveSummary[b]??={best:-Infinity,worst:-Infinity,accepted:0,phases:{}};curveSummary[b].best=Math.max(curveSummary[b].best,bestEval.value);curveSummary[b].worst=Math.max(curveSummary[b].worst,bestEval.worst);if(accept)curveSummary[b].accepted++;curveSummary[b].phases[c.phase]=(curveSummary[b].phases[c.phase]||0)+1;history.push({iteration:i,phase:c.phase,accepted:accept,candidate:+ev.value.toFixed(5),best:+bestEval.value.toFixed(5),worst:+bestEval.worst.toFixed(5),drift:+bestEval.drift.toFixed(4),plateau});}
const sourceChecks={};for(const f of ['polygon-rush/v14.6/source/part03.txt','polygon-rush/v14.6/source/part04.txt','polygon-rush/v14.6/source/part05.txt','polygon-rush/v14.6/source/part06.txt','polygon-rush/box3d/box3d_bridge.c']){const txt=fs.readFileSync(f,'utf8');sourceChecks[f]={exists:true,hasFiveRacerLogic:/for\(let i=0;i<4;i\+\+\)|ais\.length!==4|\/5/.test(txt),hasBox3D:/BOX3D|pr_b3_/.test(txt),hasRaceStart:/function start\(|raceStarted/.test(txt),hasRecovery:/recover|respawn/i.test(txt)};}
const report={method:'Polygon Rush Adaptive L3N-1000 Learning Curve v3',iterations:ITERATIONS,baseline:BASE,baselineEvaluation:evaluate(BASE),bestParameters:best,bestEvaluation:bestEval,acceptedIterations:accepted,learning:{strategy:'multi-condition robust optimization + staged curve + plateau escape + elite memory + trust-region regularization + boundary-overfit penalty',conditions:['dry/high-grip','mixed grip/load','low-grip stress'],curveSummary,eliteCount:elites.length},sourceChecks,protectedRules:['player controls functional','4 AI opponents','5 Box3D racer bodies','finite physics states','no embedded spawn','1/60 fixed step + 4 substeps','worst-case handling may not regress materially','boundary-hugging candidates penalized','runtime physics gate required before promotion'],history};fs.mkdirSync('polygon-rush/l3n/out',{recursive:true});fs.writeFileSync('polygon-rush/l3n/out/L3N1000_REPORT.json',JSON.stringify(report,null,2));console.log(JSON.stringify({iterations:ITERATIONS,accepted,baseline:report.baselineEvaluation.value,best:bestEval.value,worst:bestEval.worst,bestParameters:best,curveSummary},null,2));