import fs from 'node:fs';
const file=process.argv[2]||'polygon-rush/production/index.html';
let s=fs.readFileSync(file,'utf8');
const must=(c,m)=>{if(!c)throw new Error(m)};
s=s.replaceAll('Polygon Rush v16.0.3 Working Vehicle Restore','Polygon Rush v16.0.4 Reference Vehicle Dynamics');
s=s.replaceAll('v16.0.3 WORKING VEHICLE RESTORE','v16.0.4 REFERENCE VEHICLE DYNAMICS');
s=s.replaceAll('v16.0.3 • WORKING PHYSICS RESTORED • LARGER VISUAL WHEELS','v16.0.4 • PER-WHEEL TIRE FORCES • ACKERMANN • COMBINED GRIP');
s=s.replace("const VERSION='16.0.3'","const VERSION='16.0.4'");
const oldP="const P={mass:1180,inertia:new THREE.Vector3(1380,2180,1540),wheelBase:2.72,track:CAR.physicsTrack,wheelRadius:CAR.physicsWheelRadius,suspensionRest:.46,suspensionTravel:.30,springK:30000,damperC:4600,tireMu:1.30,cornerStiffness:8.8,longStiffness:7.2,engineForce:9200,brakeForce:13000,handbrakeForce:7000,steerMax:.60,steerRate:4.8,aeroDrag:.34,rolling:34,chassisHalf:new THREE.Vector3(CAR.width*.5,.60,CAR.length*.5)};";
const newP="const P={mass:1180,inertia:new THREE.Vector3(1380,2180,1540),wheelBase:2.72,track:CAR.physicsTrack,wheelRadius:CAR.physicsWheelRadius,suspensionRest:.46,suspensionTravel:.30,springK:30000,damperC:4600,tireMu:1.32,cornerStiffness:7.4,longStiffness:6.2,engineForce:9200,brakeForce:13000,handbrakeForce:7000,steerMax:.60,steerRate:4.8,aeroDrag:.34,rolling:34,chassisHalf:new THREE.Vector3(CAR.width*.5,.60,CAR.length*.5),cgHeight:.52,frontBrakeBias:.62,driveBiasRear:1.0,relaxLong:8.5,relaxLat:10.5,lowSpeedGrip:3.0};";
must(s.includes(oldP),'physics block missing');s=s.replace(oldP,newP);
s=s.replace("const car={pos:new THREE.Vector3(0,1.05,8),vel:new THREE.Vector3(),euler:new THREE.Euler(0,0,0,'YXZ'),quat:new THREE.Quaternion(),omega:new THREE.Vector3(),steer:0,throttle:0,brake:0,handbrake:0,contacts:[],grounded:false,speed:0,slip:0};","const car={pos:new THREE.Vector3(0,1.05,8),vel:new THREE.Vector3(),euler:new THREE.Euler(0,0,0,'YXZ'),quat:new THREE.Quaternion(),omega:new THREE.Vector3(),steer:0,throttle:0,brake:0,handbrake:0,contacts:[],grounded:false,speed:0,slip:0,wheelState:Array.from({length:4},()=>({fx:0,fy:0,spin:0}))};");
s=s.replace("car.omega.set(0,0,0);car.steer=0}","car.omega.set(0,0,0);car.steer=0;for(const w of car.wheelState){w.fx=0;w.fy=0;w.spin=0}}")
const a=s.indexOf('function rampSurface('),b=s.indexOf('function solveObstacleCollisions()',a);must(a>=0&&b>a,'vehicle force section missing');
const logic=`function rampSurface(r,x,z){const c=Math.cos(-r.heading),ss=Math.sin(-r.heading),dx=x-r.x,dz=z-r.z,lx=dx*c-dz*ss,lz=dx*ss+dz*c;if(Math.abs(lx)>r.w/2||Math.abs(lz)>r.l/2)return null;const t=clamp((lz+r.l/2)/r.l,0,1),y=t*r.h,slope=Math.atan2(r.h,r.l),n=new THREE.Vector3(0,Math.cos(slope),-Math.sin(slope)).applyAxisAngle(new THREE.Vector3(0,1,0),r.heading).normalize();return{y,normal:n,type:'ramp'}}
function surfaceAt(x,z){let best={y:0,normal:new THREE.Vector3(0,1,0),type:'ground'};for(const r of ramps){const h=rampSurface(r,x,z);if(h&&h.y>best.y)best=h}return best}
function pointVelocity(r){return car.vel.clone().add(car.omega.clone().cross(r))}function applyForce(f,r,fs,ts){fs.add(f);ts.add(r.clone().cross(f))}
function ackermannAngle(i){if(i>=2||Math.abs(car.steer)<1e-4)return 0;const sign=Math.sign(car.steer),base=Math.abs(car.steer),R=P.wheelBase/Math.max(.05,Math.tan(base)),inside=Math.atan(P.wheelBase/Math.max(.25,R-P.track*.5)),outside=Math.atan(P.wheelBase/(R+P.track*.5));const isLeft=i===0,insideWheel=sign>0?isLeft:!isLeft;return sign*(insideWheel?inside:outside)}
function wheelContact(i,dt,fs,ts){const local=wheelLocal[i],mount=local.clone().applyQuaternion(car.quat).add(car.pos),down=new THREE.Vector3(0,-1,0).applyQuaternion(car.quat).normalize();if(down.y>-0.16)return null;const surf=surfaceAt(mount.x,mount.z),rayDist=(mount.y-(surf.y+P.wheelRadius))/Math.max(.16,-down.y),maxLen=P.suspensionRest+P.suspensionTravel;if(rayDist<0||rayDist>maxLen)return null;const contact=mount.clone().addScaledVector(down,rayDist),compression=clamp(P.suspensionRest-rayDist,-P.suspensionTravel,P.suspensionTravel),r=contact.clone().sub(car.pos),pv=pointVelocity(r),axis=down.clone().negate(),suspVel=pv.dot(axis),spring=Math.max(0,P.springK*compression-P.damperC*suspVel),n=surf.normal.clone();applyForce(n.clone().multiplyScalar(spring),r,fs,ts);
 const steer=ackermannAngle(i),fwd=new THREE.Vector3(Math.sin(steer),0,Math.cos(steer)).applyQuaternion(car.quat),tangentF=fwd.clone().addScaledVector(n,-fwd.dot(n)).normalize(),side=n.clone().cross(tangentF).normalize(),longV=pv.dot(tangentF),latV=pv.dot(side),alpha=Math.atan2(latV,Math.max(.8,Math.abs(longV))),ws=car.wheelState[i];
 const drive=i>=2?car.throttle*P.engineForce*.5:0,brakeShare=i<2?P.frontBrakeBias*.5:(1-P.frontBrakeBias)*.5,brake=car.brake*P.brakeForce*brakeShare*Math.sign(longV||1)+(car.handbrake&&i>=2?P.handbrakeForce*.5*Math.sign(longV||1):0),targetFx=drive-brake-P.longStiffness*longV*38,targetFy=-P.cornerStiffness*alpha*spring*.115,rx=1-Math.exp(-P.relaxLong*dt),ry=1-Math.exp(-P.relaxLat*dt);ws.fx=lerp(ws.fx,targetFx,rx);ws.fy=lerp(ws.fy,targetFy,ry);
 const mu=P.tireMu*(.92+.08*clamp(Math.abs(longV)/8,0,1)),maxF=Math.max(P.lowSpeedGrip,mu*spring),usage=Math.hypot(ws.fx,ws.fy)/maxF;if(usage>1){ws.fx/=usage;ws.fy/=usage}applyForce(tangentF.clone().multiplyScalar(ws.fx).add(side.clone().multiplyScalar(ws.fy)),r,fs,ts);ws.spin=longV/P.wheelRadius;return{index:i,contact,normal:n,compression,spring,longV,latV,slip:alpha,steer,fx:ws.fx,fy:ws.fy}}
`;
s=s.slice(0,a)+logic+s.slice(b);
s=s.replace("if(i<2)w.rotation.y=car.steer","if(i<2)w.rotation.y=ackermannAngle(i)");
s=s.replace("spring:+c.spring.toFixed(1),slip:+c.slip.toFixed(3)","spring:+c.spring.toFixed(1),slip:+c.slip.toFixed(3),steer:+c.steer.toFixed(3),fx:+c.fx.toFixed(1),fy:+c.fy.toFixed(1)");
s=s.replace("workingVehicleTuneRestored:true","workingVehicleTuneRestored:true,referenceVehicleDynamics:true,ackermannSteering:true,combinedGrip:true,perWheelRelaxation:true");
s += '\n<!-- v16.0.4 reference-based vehicle logic: PhysX-style suspension query/load, per-wheel tangent forces, Ackermann steering, friction-circle combined grip, force relaxation -->\n';
for(const x of ["VERSION='16.0.4'","function ackermannAngle","combinedGrip:true","perWheelRelaxation:true"])must(s.includes(x),'missing '+x);fs.writeFileSync(file,s);console.log('v16.0.4 reference vehicle dynamics applied');