import fs from 'node:fs';
const file=process.argv[2];let s=fs.readFileSync(file,'utf8');
const must=(c,m)=>{if(!c)throw new Error(m)};
must(s.includes("VERSION='16.0.4'"),'expected v16.0.4');
s=s.replace("VERSION='16.0.4'","VERSION='16.0.5'").replaceAll('v16.0.4','v16.0.5').replace('Reference Vehicle Dynamics</title>','Android Touch Controls</title>').replace('REFERENCE VEHICLE DYNAMICS','ANDROID TOUCH CONTROLS').replace('PER-WHEEL TIRE FORCES • ACKERMANN • COMBINED GRIP','ANDROID TOUCH • ANALOG STEERING • GAS / BRAKE / HANDBRAKE');
s=s.replace('</style>',`#mobileControls{position:fixed;z-index:8;inset:0;display:none;pointer-events:none;touch-action:none;user-select:none;-webkit-user-select:none}#mobileControls.on{display:block}.touchZone{position:absolute;pointer-events:auto;touch-action:none}.steerPad{left:max(14px,env(safe-area-inset-left));bottom:max(18px,env(safe-area-inset-bottom));width:156px;height:156px;border:2px solid #ffffff38;border-radius:50%;background:#06101a70;backdrop-filter:blur(5px)}.steerKnob{position:absolute;left:50%;top:50%;width:66px;height:66px;transform:translate(-50%,-50%);border-radius:50%;background:#72e6a6aa;border:2px solid #ffffff88;box-shadow:0 4px 18px #0008}.pedals{right:max(14px,env(safe-area-inset-right));bottom:max(18px,env(safe-area-inset-bottom));display:grid;grid-template-columns:82px 94px;grid-template-rows:74px 74px;gap:10px;pointer-events:none}.touchBtn{pointer-events:auto;touch-action:none;border:2px solid #ffffff42;border-radius:18px;background:#071018b8;color:#fff;font-weight:950;font-size:15px;display:flex;align-items:center;justify-content:center;box-shadow:0 5px 18px #0008}.touchBtn.active{transform:scale(.96);background:#72e6a6cc;color:#071018}.gas{grid-column:2;grid-row:1 / span 2;background:#164b35c9}.brake{grid-column:1;grid-row:2;background:#5b2020c9}.handbrake{grid-column:1;grid-row:1;font-size:12px}.resetTouch{position:absolute;right:max(14px,env(safe-area-inset-right));top:max(72px,env(safe-area-inset-top));width:54px;height:54px;border-radius:50%;font-size:12px}body.mobile-game #hud{right:74px}@media (max-width:700px){#menu{width:calc(100vw - 28px)}#hud .h{min-width:70px;padding:5px 7px}.v{font-size:15px}}
</style>`);
s=s.replace('<div id="hud">','<div id="mobileControls" aria-label="Android driving controls"><div id="steerPad" class="touchZone steerPad"><div id="steerKnob" class="steerKnob"></div></div><div class="touchZone pedals"><div id="handbrakeTouch" class="touchBtn handbrake">HANDBRAKE</div><div id="gasTouch" class="touchBtn gas">GAS</div><div id="brakeTouch" class="touchBtn brake">BRAKE</div></div><div id="resetTouch" class="touchBtn resetTouch">RESET</div></div>\n<div id="hud">');
s=s.replace("const car={pos:","const touchInput={enabled:false,steer:0,throttle:0,brake:0,handbrake:0};\nconst car={pos:");
const old=`function updateInput(dt){const throttle=(keys.KeyW||keys.ArrowUp)?1:0,reverse=(keys.KeyS||keys.ArrowDown)?1:0;car.throttle=lerp(car.throttle,throttle,1-Math.exp(-8*dt));car.brake=lerp(car.brake,reverse,1-Math.exp(-10*dt));car.handbrake=keys.Space?1:0;const target=((keys.KeyA||keys.ArrowLeft)?1:0)-((keys.KeyD||keys.ArrowRight)?1:0),steerTarget=target*P.steerMax;car.steer+=clamp(steerTarget-car.steer,-P.steerRate*dt,P.steerRate*dt)}`;
const neu=`function updateInput(dt){const keyThrottle=(keys.KeyW||keys.ArrowUp)?1:0,keyBrake=(keys.KeyS||keys.ArrowDown)?1:0;const throttle=Math.max(keyThrottle,touchInput.throttle),reverse=Math.max(keyBrake,touchInput.brake);car.throttle=lerp(car.throttle,throttle,1-Math.exp(-8*dt));car.brake=lerp(car.brake,reverse,1-Math.exp(-10*dt));car.handbrake=(keys.Space||touchInput.handbrake)?1:0;const keySteer=((keys.KeyA||keys.ArrowLeft)?1:0)-((keys.KeyD||keys.ArrowRight)?1:0),target=Math.abs(touchInput.steer)>.015?touchInput.steer:keySteer,steerTarget=target*P.steerMax;car.steer+=clamp(steerTarget-car.steer,-P.steerRate*dt,P.steerRate*dt)}
function setupMobileControls(){const coarse=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;if(!coarse)return;touchInput.enabled=true;document.body.classList.add('mobile-game');const controls=$('#mobileControls'),pad=$('#steerPad'),knob=$('#steerKnob');controls.classList.add('on');const steer=e=>{e.preventDefault();const r=pad.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,rad=r.width*.38,nx=clamp(dx/rad,-1,1),ny=clamp(dy/rad,-1,1);touchInput.steer=-nx;knob.style.transform='translate(calc(-50% + '+(nx*rad*.72)+'px),calc(-50% + '+(ny*rad*.28)+'px))'};pad.addEventListener('pointerdown',e=>{pad.setPointerCapture(e.pointerId);steer(e)});pad.addEventListener('pointermove',e=>{if(pad.hasPointerCapture(e.pointerId))steer(e)});const releaseSteer=e=>{touchInput.steer=0;knob.style.transform='translate(-50%,-50%)';try{pad.releasePointerCapture(e.pointerId)}catch{}};pad.addEventListener('pointerup',releaseSteer);pad.addEventListener('pointercancel',releaseSteer);const bind=(id,key)=>{const el=$(id),set=(v,e)=>{e.preventDefault();touchInput[key]=v;el.classList.toggle('active',!!v)};el.addEventListener('pointerdown',e=>{el.setPointerCapture(e.pointerId);set(1,e)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(ev,e=>set(0,e))};bind('#gasTouch','throttle');bind('#brakeTouch','brake');bind('#handbrakeTouch','handbrake');$('#resetTouch').addEventListener('pointerdown',e=>{e.preventDefault();resetCar();$('#resetTouch').classList.add('active')});$('#resetTouch').addEventListener('pointerup',()=>$('#resetTouch').classList.remove('active'));window.addEventListener('contextmenu',e=>{if(running)e.preventDefault()});}
setupMobileControls();`;
must(s.includes(old),'input block missing');s=s.replace(old,neu);
s=s.replace("window.__polygonRush={version:VERSION,diagnostics:()=>({", "window.__polygonRush={version:VERSION,mobileControls:()=>({...touchInput}),diagnostics:()=>({mobileTouch:touchInput.enabled,");
s += '\n<!-- v16.0.5 Android/mobile multitouch controls: analog steering pad, gas, brake, handbrake, reset; Pointer Events + pointer capture + touch-action none -->\n';
fs.writeFileSync(file,s);console.log('patched',file,'to v16.0.5');